# Generated by Django 4.0.6 on 2022-07-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Familia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='altura',
            field=models.FloatField(),
        ),
    ]
